### ISSUE TITLE
Coinbase Pro Api deprecated 

### ISSUE THREAD

**Issue by Faithtosin** [kilnfi/eth-validator-watcher#107]
Coinbase Pro API is deprecated 

Calls to https://api.pro.coinbase.com/products/ETH-USD/trades now fail with this response.

```
{
  "message": "Coinbase Pro API is deprecated."
}
```

**Comment by aimxhaisse** [comment]
Thanks for opening this issue! I'll send a fix soon :)

**Comment by aimxhaisse** [comment]
Fixed in v1.0.0-beta.4
